services:
  # The Redis Database + GUI
  redis:
    image: redis/redis-stack:latest
    container_name: librarian-desk
    ports:
      - "6379:6379"   # The actual Redis port
      - "8001:8001"   # The GUI (RedisInsight) - open this in your browser

    restart: always
